<?php

return [
    'item-master' => [
        'SKU STATUS',
        'SKU LEGEND',
        'UPC CODE',
        'SUPPLIER ITEM CODE',
        'MODEL NUMBER',
        'ITEM DESCRIPTION',
        'APPLE LOB',
        'APPLE REPORT INCLUSION',
        'BRAND DESCRIPTION',
        'MARGIN CATEGORY',
        'CATEGORY DESCRIPTION',
        'CLASS DESCRIPTION',
        'SUBCLASS',
        'WAREHOUSE CATEGORY',
        'MODEL',
        'YEAR LAUNCH',
        'MODEL SPECIFIC DESCRIPTION',
        'COMPATIBILITY',
        'SIZE',
        'SIZE CODE',
        'LENGTH',
        'WIDTH',
        'HEIGHT',
        'WEIGHT',
        'ACTUAL COLOR',
        'MAIN COLOR DESCRIPTION',
        'UOM CODE',
        'VENDOR TYPE CODE',
        'INVENTORY TYPE',
        'SKU CLASS',
        'BASEUS',
        'BTB',
        'DISTRI CON',
        'DISTRI OUT',
        'DW',
        'DW MACHINE',
        'GUAM',
        // 'OMG',
        'ONLINE',
        'FRANCHISE',
        'NEW STORE',
        'MI',
        'OPENSOURCE',
        'ORIGINAL SRP',
        'CURRENT SRP',
        'DG SRP',
        'PRICE CHANGE',
        'PRICE CHANGE DATE',
        'STORE COST',
        'STORE MARGIN PERCENTAGE',
        'WORKING STORE COST',
        'WORKING STORE MARGIN PERCENTAGE',
        'MAX CONSIGNMENT RATE PERCENTAGE',
        'MOQ',
        'INCOTERMS',
        'CURRENCY',
        'SUPPLIER COST',
        'LANDED COST',
        'WORKING LANDED COST',
        'VENDOR NAME',
        'SERIAL CODE',
        'IMEI CODE 1',
        'IMEI CODE 2'
    ],
    'gashapon-item-master' => [
        'JAN NUMBER',
        'ITEM NUMBER',
        'SAP NUMBER',
        'BRAND DESCRIPTION',
        'SKU STATUS',
        'ITEM DESCRIPTION',
        'MODEL',
        'WH CATEGORY DESCRIPTION',
        'MSRP JPY',
        'CURRENT SRP',
        'NUMBER OF TOKENS',
        'DP PER CTN',
        'PCS PER DP',
        'MOQ',
        'NUMBER OF CTN',
        'NUMBER OF ASSORT',
        'COUNTRY OF ORIGIN',
        'INCOTERMS',
        'CURRENCY',
        'SUPPLIER COST',
        'UOM CODE',
        'INVENTORY TYPE',
        'VENDOR TYPE',
        'VENDOR GROUP NAME',
        'AGE GRADE',
        'BATTERY'
    ],
];