<?php

return [
    "item-master" => [
        "INVENTORY TYPE",
        "UPC CODE",
        "SUPPLIER ITEM CODE",
        "BRAND GROUP",
        "BRAND DIRECTION",
        "BRAND DESCRIPTION",
        "SKU STATUS",
        "SKU LEGEND",
        "ITEM DESCRIPTION",
        "MODEL",
        "MODEL SPECIFIC DESCRIPTION",
        "COMPATIBILITY",
        "APPLE LOB",
        "APPLE REPORT INCLUSION",
        "MARGIN CATEGORY DESCRIPTION",
        "CATEGORY DESCRIPTION",
        "CLASS DESCRIPTION",
        "SUBCLASS DESCRIPTION",
        "WH CATEGORY DESCRIPTION",
        "ORIGINAL SRP",
        "CURRENT SRP",
        "DG SRP",
        "VENDOR TYPE CODE",
        "MOQ",
        "INCOTERMS",
        "CURRENCY",
        "SUPPLIER COST",
        "SIZE",
        "SIZE CODE",
        "LENGTH",
        "WIDTH",
        "HEIGHT",
        "WEIGHT",
        "ACTUAL COLOR",
        "MAIN COLOR DESCRIPTION",
        "UOM CODE",
        "ACEFAST",
        "BEYOND THE BOX",
        "DIGITAL WALKER",
        "OPENSOURCE",
        "SERVICE CENTER",
        "LAZADA",
        "SHOPEE",
        "TIKTOK",
        "WEBSITE",
        "DISTRIBUTION CONSIGNMENT",
        "DISTRIBUTION OUTRIGHT",
        "FRANCHISE",
        "GUAM",
        "NEW STORE",
        "VENDOR NAME",
        "PRODUCT TYPE",
        "DEVICE UID"    
    ],
    "item-master-edit" => [
        "DIGITS CODE",
        "UPC CODE 1",
        "UPC CODE 2",
        "UPC CODE 3",
        "UPC CODE 4",
        "UPC CODE 5",
        "SUPPLIER ITEM CODE",
        "MODEL NUMBER",
        "BRAND GROUP",
        "BRAND DIRECTION",
        "BRAND DESCRIPTION",
        "SKU STATUS",
        "SKU LEGEND",
        "BRAND MARKETING",
        "ITEM DESCRIPTION",
        "MODEL",
        "MODEL SPECIFIC DESCRIPTION",
        "COMPATIBILITY",
        "APPLE LOB",
        "MARGIN CATEGORY DESCRIPTION",
        "CATEGORY DESCRIPTION",
        "CLASS DESCRIPTION",
        "SUBCLASS DESCRIPTION",
        "WH CATEGORY DESCRIPTION",
        "ORIGINAL SRP",
        "CURRENT SRP",
        "DG SRP",
        "PRICE CHANGE",
        "PRICE CHANGE DATE",
        "DURATION FROM",
        "DURATION TO",
        "SUPPORT TYPE",
        "VENDOR TYPE CODE",
        "VENDOR NAME",
        "MOQ",
        "CURRENCY",
        "SUPPLIER COST",
        "SIZE",
        "SIZE CODE",
        "LENGTH",
        "WIDTH",
        "HEIGHT",
        "WEIGHT",
        "ACTUAL COLOR",
        "MAIN COLOR DESCRIPTION",
        "UOM CODE",
        "INVENTORY TYPE",
        "ACEFAST",
        "BEYOND THE BOX",
        "DIGITAL WALKER",
        "OPENSOURCE",
        "SERVICE CENTER",
        "LAZADA",
        "SHOPEE",
        "TIKTOK",
        "WEBSITE",
        "DISTRIBUTION CONSIGNMENT",
        "DISTRIBUTION OUTRIGHT",
        "FRANCHISE",
        "GUAM",
        "NEW STORE",
        "PRODUCT TYPE",
        "DEVICE UID"   
    ],
    "gashapon-item-master" => [
        "JAN NUMBER",
        "ITEM NUMBER",
        "SAP NUMBER",
        "PRODUCT TYPE",
        "BRAND DESCRIPTION",
        "SKU STATUS",
        "ITEM DESCRIPTION",
        "MODEL",
        "CATEGORY",
        "WH CATEGORY DESCRIPTION",
        "MSRP JPY",
        "CURRENT SRP",
        "NUMBER OF TOKENS",
        "PCS PER CTN",
        "DP PER CTN",
        "PCS PER DP",
        "MOQ",        
        "ORDER CTN",
        "NUMBER OF ASSORT",
        "COUNTRY OF ORIGIN",
        "INCOTERMS",
        "CURRENCY",
        "SUPPLIER COST",
        "UOM CODE",
        "INVENTORY TYPE",
        "VENDOR TYPE",
        "VENDOR GROUP NAME",
        "AGE GRADE",
        "BATTERY"
    ],
    "gashapon-item-master-edit" => [
        "DIGITS CODE",
        "LC PER CARTON",
        "LC PER PC",
        "SC PER PC",
    ],
];